version: '2'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        # build-time ENV parameters
        RAILS_ENV: development
    ports:
      - "80:80"
    environment:
      # runtime ENV parameters
      RAILS_ENV: development
      RAILS_COOKIE_TOKEN: 8db388d70170c0ec9dedf836b5c8060c1a871b1abc2487e50ee5111be20f5740bc1aad2a2f39fb0dff88bd849db14170b96cf6f70f84cee0526920f1bd4bac25
    # not currently needed
    #volumes:
      #- ./log:/consumer_complaint/log
